rules = [
  DisableSyntax
  LeakingImplicitClassVal
  NoValInForComprehension
  ProcedureSyntax
  RedundantSyntax
  NoAutoTupling
  ArrayEquals,
  ArraysInFormat,
  ArraysToString,
  AsInstanceOf,
  AvoidSizeEqualsZero,
  AvoidSizeNotEqualsZero,
  AvoidToMinusOne,
  BigDecimalDoubleConstructor,
  BigDecimalScaleWithoutRoundingMode,
  BooleanParameter,
  BoundedByFinalType,
  BrokenOddness,
  CatchException,
  CatchExceptionImmediatelyRethrown,
  CatchFatal,
  CatchNpe,
  CatchThrowable,
  ClassNames,
  CollectionIndexOnNonIndexedSeq,
  CollectionNamingConfusion,
  CollectionNegativeIndex,
  CollectionPromotionToAny,
  ComparingFloatingPointTypes,
  ComparisonToEmptyList,
  ComparisonToEmptySet,
  ComparisonWithSelf,
  ConstantIf,
  DivideByOne,
  DoubleNegation,
  DuplicateImport,
  DuplicateMapKey,
  DuplicateSetValue,
  EitherGet,
  EmptyCaseClass,
  EmptyFor,
  EmptyIfBlock,
  EmptyInterpolatedString,
  EmptyMethod,
  EmptySynchronizedBlock,
  EmptyTryBlock,
  EmptyWhileBlock,
  ExistsSimplifiableToContains,
  FilterDotHead,
  FilterDotHeadOption,
  FilterDotIsEmpty,
  FilterDotSize,
  FilterOptionAndGet,
  FinalModifierOnCaseClass,
  FinalizerWithoutSuper,
  FindAndNotEqualsNoneReplaceWithExists,
  FindDotIsDefined,
  IllegalFormatString,
  ImpossibleOptionSizeCondition,
  IncorrectNumberOfArgsToFormat,
  IncorrectlyNamedExceptions,
  InterpolationToString,
  InvalidRegexTest,
  IsInstanceOf,
  LonelySealedTrait,
  LooksLikeInterpolatedString,
  MapGetAndGetOrElse,
  MethodReturningAny,
  NanComparison,
  NullAssignment,
  NullParameter,
  OptionGet,
  OptionSize,
  RepeatedCaseBody,
  RepeatedIfElseBody,
  StripMarginOnRegex,
  SwallowedException,
  TryGet,
  UnnecessaryConversion,
  UnreachableCatch,
  UnsafeContains,
  UnsafeStringContains,
  UnsafeTraversableMethods,
  UnusedMethodParameter,
  VarCouldBeVal,
  VariableShadowing,
  WhileTrue
]
// Would be nice to add : DisableSyntax.noThrows = true
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
// Would be nice to add : DisableSyntax.noAsInstanceOf = true
// Would be nice to add : DisableSyntax.noIsInstanceOf = true
DisableSyntax.noFinalize = true
DisableSyntax.noValPatterns = true